SCREEN_WIDTH = 1536
SCREEN_HEIGHT = 864

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8              #change back to 0.8
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200
PLAYER_SHOOT_SPEED = 500
SHOT_RADIUS = 5
SINGLE_SHOT_FIRERATE = 0.3
TRIPLE_SHOT_FIRERATE = 0.6
GATLING_FIRERATE = 0.01
GATLING_USE_TIME = .5
GATLING_COOLDOWN = 4
MAX_LIVES = 3
GRACE_PERIOD = 2
BUFF_ATTACKSPEED_SPAWN_RATE = 20           #change back to 20
BUFF_DOUBLEPOINTS_SPAWN_RATE = 45          #change back to 45
BUFF_LENGTH = 5
GATLING_BUFF_LENGTH = 2